### ISSUE TITLE
Doesn't Work in Northern Ireland 

### ISSUE THREAD

**Issue by mikedurney** [seanmtracey/CineList-API#18]
Doesnt work with cinemas in Northern Ireland

**Comment by jimbo8098** [comment]
Which endpoints don't work? I know one or two of the endpoints only work with British town names but I'd expect postcodes should work.

**Comment by jimbo8098** [comment]
Afraid you're outta luck. Find Any Film (the site scraped for the data you're receiving) doesn't seem to support NI postcodes. I just tried a random postcode in Belfast where I'd expect some cinemas to be.
