### ISSUE TITLE
Looking up films in advanced isn't returning properly

### ISSUE THREAD

**Issue by thomhurst** [seanmtracey/CineList-API#19]
E.g. my local cineworld has film listings for next week, as I can see through their app
When I query cinelist, then none of these are visible.

**Comment by seanmtracey** [comment]
The CineList API scrapes info from findanyfilm.com to generate the results for each cinema. Much to my sorrow, the cinema chains sometimes neglect to submit their schedules to findanyfilm.com, and so I'm unable to get them also. 

Having said that, I don't want to risk dismissing this issue out of hand, it could be something else. If you can tell me what the cinema ID is for your local cinema, I'll be happy to dig a little deeper and try and figure it out.

**Comment by seanmtracey** [comment]
No response. Closing until further information is available.
