### ISSUE TITLE
Return latitude and longitude coordinates (or postcodes) for cinemas

### ISSUE THREAD

**Issue by seanmtracey** [seanmtracey/CineList-API#20]
Searching through GH repos of projects that use the CineList API, I notice that a lot of people want coordinates to map out the cinemas, but the CineList API doesn't surface any information that helps them to do it. They end up making a bunch of requests to Google to figure out where the cinemas actually are.

I could add the postcode of each cinema (which I already have access to) to the response which wouldn't impact the APIs performance, or... 

I could use the postcode to look up the coordinates (which wouldn't be _too_) hard to return approximate coordinates (the center point of the postcode for the cinema)

This comes with three considerations:
1. This will affect the speed of the CineList API, and I like that it's really fast
2. If the coordinates are wrong, people will blame CineList/me when it's the data sources fault
3. I don't personally have a need for it, but that's never stopped me before.

**Comment by jimbo8098** [comment]
Hmmm technically I don't really see why this won't be possible while querying cinemas. A cinema address is provided in the FaF site so this should be scrapeable. Lemme look into this.

**Comment by jimbo8098** [comment]
Ok this is fine, it's actually output by the cinema API we just never used it before. I'll submit a PR soon for a first version.

**Comment by jimbo8098** [comment]
There we go :)
