### ISSUE TITLE
The server where this page is located isn't responding

### ISSUE THREAD

**Issue by celine305** [seanmtracey/CineList-API#24]
Hi, 

The API doesn't seem to work anymore. When I try to open https://api.cinelist.co.uk, I get the message

"Safari can’t open the page “https://api.cinelist.co.uk” because the server where this page is located isn’t responding."

Could you please help me with this.

Also, I just want to say thanks a lot for all the work you've put into this, I love your API!

**Comment by seanmtracey** [comment]
Whoops, forgot to update payment card details. All sorted now. Thanks for letting me know! Will look at putting something together for #25

**Comment by seanmtracey** [comment]
BTW, Thanks for the kind words! Glad you like it :)
