### ISSUE TITLE
Add an option for showing subtitled showings

### ISSUE THREAD

**Issue by j-mes** [seanmtracey/CineList-API#35]
:wave:

Could there be an option to provide results to show films that will be subtitled/captioned? This would be a great plus for the deaf/hard of hearing community, and for people who do not have English as a native language at the cinema.

At the moment, from personal experience... cinemas only show subtitled/captioned film showings twice a week, and it can be a minefield trying to find out which one to attend.

**Comment by seanmtracey** [comment]
Love this idea, will totally implement if I can find a reliable data source for this info.
