### ISSUE TITLE
API calls blocked due to mixed content - not served over HTTPS

### ISSUE THREAD

**Issue by samuelkitson** [seanmtracey/CineList-API#38]
Hi,

I am trying to call your incredibly useful api through a simple HTML web page that I am creating. However, it is on HTTPS but cinelist.co.uk is on HTTP. Unfortunately this means that all of my api calls are being blocked:

`Mixed Content: The page at 'https://my-website.com' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.cinelist.co.uk/get/cinema/10523'. This request has been blocked; the content must be served over HTTPS.`

Would it be at all possible to serve your website over HTTPS? It'd be great to be able to implement your api soon!

Thanks

**Comment by seanmtracey** [comment]
Hi there!

The CineList API is only served over HTTPS. 

The URL you're requesting is `http://api.cinelist.co.uk/get/cinema/10523` which is over HTTP. If you change your code to have `https://` instead of `http://` it should work fine :)

**Comment by samuelkitson** [comment]
Sorry - typo! I'd forgotten to change the web address in one of my functions :/

Thanks for your fast response and the great api

**Comment by seanmtracey** [comment]
Anytime! Glad you found it useful. Would love to see what you put together if it goes live :)
