### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by ckpanteli** [seanmtracey/CineList-API#39]
Hi Sean.

Thanks for making the cinelist API. I'm using it in a little Vue web app: https://ckpantelides.github.io/movietimes/

I've noticed your security certificate expired on 9 May. Do you plan on renewing it?

Thanks again

**Comment by seanmtracey** [comment]
Terribly sorry about that, I've been consumed with other projects recently and I haven't had time to give CineList the love it deserves.

The certificate has now been renewed, but I think I'll take down the API in the next few months to tidy the renewal process up, it's a bit of a pain ATM.

**Comment by ckpanteli** [comment]
Thanks for getting back to me
