### ISSUE TITLE
Is day really an offset or full date?

### ISSUE THREAD

**Issue by simonporter007** [seanmtracey/CineList-API#8]
Hi Sean,

Looks like either the FaF website changed or maybe I was just confused by the description of the day parameter. It looks as though it currently works by using a full date string (e.g. 2016-10-05) rather than an offset which I read as being days from today (e.g. same date above would be 2).

Can you confirm the correct use of the day parameter in the get endpoint?
Other than that, great little api. Just nice and clean, I like it.

**Comment by seanmtracey** [comment]
Hey Simon,

Sorry for taking so long in checking this out. You're completely correct, FaF does accept a date string. I've updated the API to convert the day parameter into the appropriate date string  (#15)

Thanks for pointing it out, and again, sorry for the delay.
